<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title><xsl:value-of select="/rss/channel/title"/> RSS Feed</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            margin: 0;
            padding: 40px;
            color: #333;
            background-color: #f9f9f9;
          }
          .container {
            max-width: 700px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            padding: 40px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
          }
          .header {
            border-bottom: 1px solid #eee;
            margin-bottom: 30px;
            padding-bottom: 30px;
          }
          h1 {
            color: #191716;
            margin: 0 0 10px 0;
            font-size: 28px;
          }
          .subtitle {
            color: #666;
            font-size: 16px;
            margin: 0;
          }
          .info {
            background: #f8f9fa;
            border-left: 4px solid #007cba;
            padding: 15px 20px;
            margin: 20px 0;
            border-radius: 0 4px 4px 0;
          }
          .info p {
            margin: 0;
            color: #555;
          }
          .posts {
            margin-top: 30px;
          }
          .post {
            margin-bottom: 30px;
            padding-bottom: 25px;
            border-bottom: 1px solid #eee;
          }
          .post:last-child {
            border-bottom: none;
          }
          .post-title {
            font-size: 20px;
            margin: 0 0 8px 0;
          }
          .post-title a {
            color: #191716;
            text-decoration: none;
          }
          .post-title a:hover {
            text-decoration: underline;
          }
          .post-date {
            color: #666;
            font-size: 14px;
            margin-bottom: 10px;
          }
          .post-excerpt {
            color: #444;
            line-height: 1.6;
          }
          .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            color: #666;
            font-size: 14px;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1><xsl:value-of select="/rss/channel/title"/></h1>
            <p class="subtitle"><xsl:value-of select="/rss/channel/description"/></p>
          </div>

          <div class="info">
            <p><strong>📡 This is an RSS feed</strong> - a way to stay updated with new posts automatically. Copy this page's URL into your RSS reader app or use the subscribe button in your browser.</p>
          </div>

          <div class="posts">
            <h2>Recent Posts</h2>
            <xsl:for-each select="/rss/channel/item">
              <div class="post">
                <h3 class="post-title">
                  <a href="{link}"><xsl:value-of select="title"/></a>
                </h3>
                <div class="post-date"><xsl:value-of select="pubDate" /></div>
                <div class="post-excerpt"><xsl:value-of select="description" disable-output-escaping="yes"/></div>
              </div>
            </xsl:for-each>
          </div>

          <div class="footer">
            <p>Generated by Jekyll • <a href="{/rss/channel/link}">← Back to website</a></p>
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>